/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WayfinderRouteImport } from './routes/wayfinder'
import { Route as UpgradesRouteImport } from './routes/upgrades'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteIndexRouteImport } from './routes/route.index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OrderStallIdRouteImport } from './routes/order.$stallId'
import { Route as OpsIncidentsRouteImport } from './routes/ops.incidents'
import { Route as OpsDispatchRouteImport } from './routes/ops.dispatch'
import { Route as OpsControlsRouteImport } from './routes/ops.controls'
import { Route as OpsChatRouteImport } from './routes/ops.chat'
import { Route as ApiForecastRouteImport } from './routes/api.forecast'
import { Route as ApiAssistantRouteImport } from './routes/api.assistant'

const WayfinderRoute = WayfinderRouteImport.update({
  id: '/wayfinder',
  path: '/wayfinder',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradesRoute = UpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIndexRoute = RouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OrderStallIdRoute = OrderStallIdRouteImport.update({
  id: '/$stallId',
  path: '/$stallId',
  getParentRoute: () => OrderRoute,
} as any)
const OpsIncidentsRoute = OpsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDispatchRoute = OpsDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => OpsRoute,
} as any)
const OpsControlsRoute = OpsControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => OpsRoute,
} as any)
const OpsChatRoute = OpsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => OpsRoute,
} as any)
const ApiForecastRoute = ApiForecastRouteImport.update({
  id: '/api/forecast',
  path: '/api/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/ops': typeof OpsRouteWithChildren
  '/order': typeof OrderRouteWithChildren
  '/queues': typeof QueuesRoute
  '/upgrades': typeof UpgradesRoute
  '/wayfinder': typeof WayfinderRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/forecast': typeof ApiForecastRoute
  '/ops/chat': typeof OpsChatRoute
  '/ops/controls': typeof OpsControlsRoute
  '/ops/dispatch': typeof OpsDispatchRoute
  '/ops/incidents': typeof OpsIncidentsRoute
  '/order/$stallId': typeof OrderStallIdRoute
  '/ops/': typeof OpsIndexRoute
  '/route/': typeof RouteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/order': typeof OrderRouteWithChildren
  '/queues': typeof QueuesRoute
  '/upgrades': typeof UpgradesRoute
  '/wayfinder': typeof WayfinderRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/forecast': typeof ApiForecastRoute
  '/ops/chat': typeof OpsChatRoute
  '/ops/controls': typeof OpsControlsRoute
  '/ops/dispatch': typeof OpsDispatchRoute
  '/ops/incidents': typeof OpsIncidentsRoute
  '/order/$stallId': typeof OrderStallIdRoute
  '/ops': typeof OpsIndexRoute
  '/route': typeof RouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/ops': typeof OpsRouteWithChildren
  '/order': typeof OrderRouteWithChildren
  '/queues': typeof QueuesRoute
  '/upgrades': typeof UpgradesRoute
  '/wayfinder': typeof WayfinderRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/forecast': typeof ApiForecastRoute
  '/ops/chat': typeof OpsChatRoute
  '/ops/controls': typeof OpsControlsRoute
  '/ops/dispatch': typeof OpsDispatchRoute
  '/ops/incidents': typeof OpsIncidentsRoute
  '/order/$stallId': typeof OrderStallIdRoute
  '/ops/': typeof OpsIndexRoute
  '/route/': typeof RouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/map'
    | '/ops'
    | '/order'
    | '/queues'
    | '/upgrades'
    | '/wayfinder'
    | '/api/assistant'
    | '/api/forecast'
    | '/ops/chat'
    | '/ops/controls'
    | '/ops/dispatch'
    | '/ops/incidents'
    | '/order/$stallId'
    | '/ops/'
    | '/route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/map'
    | '/order'
    | '/queues'
    | '/upgrades'
    | '/wayfinder'
    | '/api/assistant'
    | '/api/forecast'
    | '/ops/chat'
    | '/ops/controls'
    | '/ops/dispatch'
    | '/ops/incidents'
    | '/order/$stallId'
    | '/ops'
    | '/route'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/map'
    | '/ops'
    | '/order'
    | '/queues'
    | '/upgrades'
    | '/wayfinder'
    | '/api/assistant'
    | '/api/forecast'
    | '/ops/chat'
    | '/ops/controls'
    | '/ops/dispatch'
    | '/ops/incidents'
    | '/order/$stallId'
    | '/ops/'
    | '/route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  OpsRoute: typeof OpsRouteWithChildren
  OrderRoute: typeof OrderRouteWithChildren
  QueuesRoute: typeof QueuesRoute
  UpgradesRoute: typeof UpgradesRoute
  WayfinderRoute: typeof WayfinderRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiForecastRoute: typeof ApiForecastRoute
  RouteIndexRoute: typeof RouteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wayfinder': {
      id: '/wayfinder'
      path: '/wayfinder'
      fullPath: '/wayfinder'
      preLoaderRoute: typeof WayfinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/': {
      id: '/route/'
      path: '/route'
      fullPath: '/route/'
      preLoaderRoute: typeof RouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/order/$stallId': {
      id: '/order/$stallId'
      path: '/$stallId'
      fullPath: '/order/$stallId'
      preLoaderRoute: typeof OrderStallIdRouteImport
      parentRoute: typeof OrderRoute
    }
    '/ops/incidents': {
      id: '/ops/incidents'
      path: '/incidents'
      fullPath: '/ops/incidents'
      preLoaderRoute: typeof OpsIncidentsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/dispatch': {
      id: '/ops/dispatch'
      path: '/dispatch'
      fullPath: '/ops/dispatch'
      preLoaderRoute: typeof OpsDispatchRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/controls': {
      id: '/ops/controls'
      path: '/controls'
      fullPath: '/ops/controls'
      preLoaderRoute: typeof OpsControlsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/chat': {
      id: '/ops/chat'
      path: '/chat'
      fullPath: '/ops/chat'
      preLoaderRoute: typeof OpsChatRouteImport
      parentRoute: typeof OpsRoute
    }
    '/api/forecast': {
      id: '/api/forecast'
      path: '/api/forecast'
      fullPath: '/api/forecast'
      preLoaderRoute: typeof ApiForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpsRouteChildren {
  OpsChatRoute: typeof OpsChatRoute
  OpsControlsRoute: typeof OpsControlsRoute
  OpsDispatchRoute: typeof OpsDispatchRoute
  OpsIncidentsRoute: typeof OpsIncidentsRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsChatRoute: OpsChatRoute,
  OpsControlsRoute: OpsControlsRoute,
  OpsDispatchRoute: OpsDispatchRoute,
  OpsIncidentsRoute: OpsIncidentsRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface OrderRouteChildren {
  OrderStallIdRoute: typeof OrderStallIdRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderStallIdRoute: OrderStallIdRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  OpsRoute: OpsRouteWithChildren,
  OrderRoute: OrderRouteWithChildren,
  QueuesRoute: QueuesRoute,
  UpgradesRoute: UpgradesRoute,
  WayfinderRoute: WayfinderRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiForecastRoute: ApiForecastRoute,
  RouteIndexRoute: RouteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
